### ISSUE TITLE
Need to assign Slurm account number.

### ISSUE THREAD

**Issue by jonnyhtw** [pletzer/rosesnip#2]
Hi again

I've managed to get the cylc suites working with Slurm by inserting these lines after running `rsn_create-cylc-suite.py`...

```
#!jinja2
{% from 'hpc_project' import get_hpc_project %}  # <---- import the function
.
.
.
[runtime]
    [[root]]
        [[[directives]]]
            --account = {{ get_hpc_project() }}  # <---- find & print project code!
.
.
.
```

We need to find a way of getting this inserted by default.

Cheers 😄 

Jonny

**Comment by jonnyhtw** [comment]
I've made these changes in `rsn_create_cylc_suite.py`...
![image](https://user-images.githubusercontent.com/12940715/81144209-af44b180-8fc7-11ea-8379-5df8ee9fb48c.png)

**Comment by jonnyhtw** [comment]
... but these throws this error...

```
> python rsn_create-cylc-suite.py -d foo -s -a ~pletzera/turbofan/pletz

Run script is /scale_wlg_persistent/filesets/home/williamsjh/rosesnip/foo/rsn_run.sh.
Traceback (most recent call last):
  File "rsn_create-cylc-suite.py", line 154, in <module>
    main()
  File "rsn_create-cylc-suite.py", line 149, in main
    f.write(SUITE_RC_TEMPLATE.format(**params))
KeyError: "% from 'hpc_project' import get_hpc_project %"
```

**Comment by pletzer** [comment]
Hi @jonnyhtw,
In branch model_monitor2, the rosesnip.rc file now contains the entry
[slurm]
  account = nesi12345

It is also possible to pass the account information to rsn_create-cylc-suite.py:
$ python rsn_create-cylc-suite.py -h
usage: rsn_create-cylc-suite.py [-h] [-d RESULT_DIR] [-a ABRUN_EXEC]
                                [-A APP_NAME] [-m MAX_NUM_CONCURRENT_JOBS]
                                [-I] [-p PYTHON_EXEC] [-L EXEC_TIME_LIMIT]
                                [--account ACCOUNT]

Generate CYLC suite.rc file.

optional arguments:
  -h, --help            show this help message and exit
  -d RESULT_DIR         specify result directory (output of rsn_prepare.py)
  -a ABRUN_EXEC         full path to abrun.sh executable
  -A APP_NAME           name of afterburner app
  -m MAX_NUM_CONCURRENT_JOBS
                        max number of concurrent jobs
  -I                    create suite.rc file for for interactive execution
                        (default is SLURM)
  -p PYTHON_EXEC        path to python executable
  -L EXEC_TIME_LIMIT    execution time limit for each task
  --account ACCOUNT     SLURM account number
