### ISSUE TITLE
afterburner needs python 2 to be able to restart

### ISSUE THREAD

**Issue by pletzer** [pletzer/rosesnip#4]
For some obscure reasons I found that although afterburner is happy to run under Python 3 but the netcdf files saved in the cache will not be loaded when restarting. This problem does not arise with python2.

**Comment by pletzer** [comment]
Maybe an order problem?

After loading Anaconda3/2020...

w-mauivlab02/nesi/nobackup/pletzera/rosesnip/rose-app-expanded-full$ export SCITOOLS_MODULE=none
w-mauivlab02/nesi/nobackup/pletzera/rosesnip/rose-app-expanded-full$ export PYTHON_EXEC=$(which python)

w-mauivlab02/nesi/nobackup/pletzera/rosesnip/rose-app-expanded-full$ /nesi/nobackup/nesi99999/pletzera/niwa00013/nesi/turbofan/trunk/bin/abrun.sh ModelMonitor2 -c /scale_wlg_nobackup/filesets/nobackup/pletzera/rosesnip/rose-app-expanded-full/rose-app-expanded-full.conf -v
/opt/nesi/CS500_centos7_skl/Anaconda3/2020.02-GCC-7.1.0/bin/python /scale_wlg_nobackup/filesets/nobackup/nesi99999/pletzera/niwa00013/nesi/turbofan/trunk/bin/abrun.py ModelMonitor2 -c /scale_wlg_nobackup/filesets/nobackup/pletzera/rosesnip/rose-app-expanded-full/rose-app-expanded-full.conf -v
which: no moo in (/opt/nesi/CS500_centos7_skl/Anaconda3/2020.02-GCC-7.1.0:/opt/nesi/CS500_centos7_skl/Anaconda3/2020.02-GCC-7.1.0/sbin:/opt/nesi/CS500_centos7_skl/Anaconda3/2020.02-GCC-7.1.0/bin:/opt/nesi/CS500_centos7_skl/binutils/2.28-GCCcore-7.1.0/bin:/opt/nesi/CS500_centos7_skl/GCCcore/7.1.0/bin:/opt/nesi/CS400_centos7_bdw/Anaconda3/2019.03-gimkl-2018b/bin:/opt/nesi/CS400_centos7_bdw/Anaconda3/2019.03-gimkl-2018b/condabin:/home/pletzera/.local/bin:/opt/slurm/sbin:/opt/slurm/bin:/opt/nesi/share/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/sbin:/usr/sbin:/cm/local/apps/environment-modules/3.2.10/bin:/opt/nesi/bin:/home/pletzera/bin)
ERROR: [umfilelist.<module>:247] Unable to find 'moo' command in runtime environment.
Initialising ModelMonitor2 app...
Initialising StreamSplit data cache...
Running ModelMonitor2 app...

Refreshing data caches for model u-az513...

Loading cached netCDF data for u-az513/apy/m01s00i024/lev0/land+sea/Global/awmean...
Loading latest model data for u-az513/apy/m01s00i024...

**Comment by pletzer** [comment]
Taking out model az513, everything  gets loaded quickly with python3.

**Comment by jonnyhtw** [comment]
This issue does not apply any more since the solution to it is now understood, that is, a `start_date` and `end_date` are required to make sure that each simulation is not read in again from scratch.

Thanks!

Jonny
