### ISSUE TITLE
Merge stuff in my fork to enable issue tracking?

### ISSUE THREAD

**Issue by jonnyhtw** [pletzer/rosesnip#7]
Hey @pletzer 

I've made a few changes in my fork and want enable issue tracking to solve something. It looks like issues aren't available in a fork though.

Any recommendations?

Thanks!

Jonny

**Comment by pletzer** [comment]
Hi @jonnyhtw,

Not sure... Sorry...

**Comment by jonnyhtw** [comment]
Oh no worries. I fixed the issue now anyway! 😀
